-   id: graphene-django-hook
    name: graphene django schema hook
    description: Generate graphql schema.
    entry: entrypoint.sh
    language: script
    'types': [python]
    always_run: true
    pass_filenames: false
    minimum_pre_commit_version: 0.14.0
